# Generated by Django 5.2.6 on 2025-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('center-back', 'Center-Back'), ('left-back', 'Left-Back'), ('right-back', 'Right-Back'), ('center-midfielder', 'Center-Midfielder'), ('attacking-midfielder', 'Attacking-Midfielder'), ('defensive-midfielder', 'Defensive-Midfielder'), ('left-winger', 'Left-Winger'), ('right-winger', 'Right-Winger'), ('striker', 'Striker')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('club', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.FloatField()),
            ],
        ),
    ]
