# Generated by Django 5.2.6 on 2025-09-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Player',
        ),
    ]
